export const FETCHNEXTPOSTS = "FETCHNEXTPOSTS";
export const LOADINGAPOST = "LOADINGAPOST";
export const GOTAPOST = "GOTAPOST";
export const ALLPOSTSRETRIEVED = "ALLPOSTSRETRIEVED";
export const LOADINGPOSTS = "LOADINGPOSTS";
